Repository project-lighter/lighter, pull requests merged in 2025-02, with the labels that each got.

#147 Docs
  .gitignore
  README.md
  assets/images/features_dark.png
  assets/images/features_light.png
  docs/advanced/callbacks.md
  docs/advanced/inferer.md
  docs/advanced/postprocessing.md
  docs/assets/extra.css
  docs/assets/images/Lighter_demo.png
  docs/assets/images/PL_demo.png
  docs/basics/config.md
  docs/basics/projects.md
  docs/basics/quickstart.md
  docs/basics/workflows.md
  docs/design/overview.md
  docs/how-to/adapters.md
  docs/how-to/configure.md
  docs/how-to/freezers.md
  docs/how-to/inferers.md
  docs/how-to/metrics.md
  docs/how-to/project_module.md
  docs/how-to/run.md
  docs/how-to/writers.md
  docs/index.md
  docs/overrides/404.css
  docs/overrides/404.html
  docs/overrides/components/component.css
  docs/overrides/components/component.html
  docs/overrides/components/component1.css
  docs/overrides/components/component1.html
  docs/overrides/components/feature-card2.css
  docs/overrides/components/feature-card2.html
  docs/overrides/components/feature-card3.css
  docs/overrides/components/feature-card3.html
  docs/overrides/components/feature-card4.css
  docs/overrides/components/feature-card4.html
  docs/overrides/components/gallery-card3.css
  docs/overrides/components/gallery-card3.html
  docs/overrides/components/navigation-links.css
  docs/overrides/components/navigation-links.html
  docs/overrides/components/navigation-links1.css
  docs/overrides/components/navigation-links1.html
  docs/overrides/components/navigation-links2.css
  docs/overrides/components/navigation-links2.html
  docs/overrides/components/navigation-links3.css
  docs/overrides/components/navigation-links3.html
  docs/overrides/index.css
  docs/overrides/index.html
  docs/overrides/package.json
  docs/overrides/style.css
  docs/tutorials/configuration_basics.md
  docs/tutorials/image_classification.md
  lighter/__init__.py
  lighter/adapters.py
  lighter/system.py
  mkdocs.yml
  pyproject.toml
  uv.lock
Labels: size:XXL

#149 Updates
  paper/paper.md
Labels: size:S

#150 Add joss paper draft
  .github/workflows/docs-publish.yml
  .gitignore
  README.md
  mkdocs.yml
  paper/lighter_diagrams.pptx
  paper/overview_all.png
  paper/overview_system.png
  paper/paper.bib
  paper/paper.md
Labels: size:L
