Repository project-lighter/lighter, pull requests merged in 2025-05, with the labels that each got.

#159 Improve usage of uv
  CONTRIBUTING.md
  Makefile
  pyproject.toml
  uv.lock
Labels: size:M

#160 Remove upper bounds of dependencies
  Makefile
  lighter/adapters.py
  lighter/system.py
  pyproject.toml
  uv.lock
Labels: size:M

#155 Remove lightly
  pyproject.toml
  uv.lock
Labels: size:XS

#161 Enable blank issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: size:XS

#157 Fix classification tutorial
  docs/tutorials/image_classification.md
Labels: size:M

#162 Fix metric registration
  lighter/system.py
  lighter/utils/patches.py
  lighter/utils/types/containers.py
  tests/unit/test_system.py
Labels: size:L

#164 Updating pre-commit hook
  .pre-commit-config.yaml
Labels: size:XS
